apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lifecycle-agent
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cert-manager-operator
  namespace: cert-manager-operator
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lifecycle-agent
  namespace: openshift-lifecycle-agent
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: bapalm-cert-manager-poc
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: ${CERT_MANAGER_CATALOG_IMAGE}
  displayName: bapalm cert-manager POC
  publisher: bapalm
  updateStrategy:
    registryPoll:
      interval: 10m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: bapalm-lifecycle-agent-poc
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: ${LCA_CATALOG_IMAGE}
  displayName: bapalm lifecycle-agent POC
  publisher: bapalm
  updateStrategy:
    registryPoll:
      interval: 10m
